# Use postgres/example user/password credentials
version: '3.9'

services:

  plo:
    container_name: plo
    image: plo
    volumes:
      - ./models:/app/models
      - ./game/Backend:/app/
      - ./logs:/app/logs
    ports:
      - 8765:8765
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./launch_deps:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432

