# Generated by Django 5.0.7 on 2024-07-28 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlopTexture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PotType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BetSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                (
                    "flop_texture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.floptexture",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.player",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.position",
                    ),
                ),
                (
                    "pot_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.pottype",
                    ),
                ),
            ],
            options={
                "unique_together": {("pot_type", "position", "player", "flop_texture")},
            },
        ),
        migrations.CreateModel(
            name="BetFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hand", models.CharField(max_length=10)),
                ("player1_frequency", models.IntegerField()),
                ("player2_frequency", models.IntegerField()),
                (
                    "flop_texture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.floptexture",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player1_frequencies",
                        to="decision_tree.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player2_frequencies",
                        to="decision_tree.player",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.position",
                    ),
                ),
                (
                    "pot_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decision_tree.pottype",
                    ),
                ),
            ],
            options={
                "unique_together": {("pot_type", "position", "flop_texture", "hand")},
            },
        ),
    ]
